# Generated by Django 4.2.27 on 2026-01-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, help_text='Commentaires et explications'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='location',
            field=models.CharField(blank=True, help_text='Où utiliser ce snippet (ex: shell, settings.py, views.py)', max_length=100),
        ),
    ]
