# Generated by Django 4.2.27 on 2026-01-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_description_snippet_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='location',
            field=models.CharField(blank=True, help_text='Où utiliser ce snippet (ex: shell, venv, settings.py, views.py)', max_length=100),
        ),
    ]
